# Generated by Django 2.2.6 on 2020-01-11 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_german', models.CharField(max_length=200)),
                ('title_english', models.CharField(max_length=200)),
                ('text_german', models.TextField()),
                ('text_english', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='', upload_to='static_prod/EventImages/')),
                ('main', models.BooleanField(default=False)),
                ('whichEvent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Foerder.Event')),
            ],
        ),
    ]
